/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.gui;

import client.CommandResponseReceiver;
import client.CommandSender;
import commonModule.commands.commandObjects.HelpCommand;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author dmitrii_andriianov
 */
public class ApplicationWindow extends javax.swing.JFrame {

    private final CommandSender commandSender;
    private final CommandResponseReceiver commandResponseReceiver;

    /**
     * Creates new form ApplicationWindow
     */
    public ApplicationWindow(CommandSender commandSender, CommandResponseReceiver commandResponseReceiver) {
        initComponents();

        this.commandSender = commandSender;
        this.commandResponseReceiver = commandResponseReceiver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        usernameIconLabel = new javax.swing.JLabel();
        interactionPanel = new javax.swing.JPanel();
        pigImagePanel = new javax.swing.JLabel();
        commandsButtonsPanel = new javax.swing.JPanel();
        helpButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        executeScriptButton = new javax.swing.JButton();
        removeLowerButton = new javax.swing.JButton();
        replaceIfGreaterButton = new javax.swing.JButton();
        removeGreaterButton = new javax.swing.JButton();
        countImpactSpeedButton = new javax.swing.JButton();
        filterCarButton = new javax.swing.JButton();
        uniqieMoodButton = new javax.swing.JButton();
        emptyResetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(222, 100, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        usernameLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(71, 199, 231));
        usernameLabel.setText("Username");

        usernameIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/username_icon.png"))); // NOI18N

        pigImagePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pigImagePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/translucent-pig.png"))); // NOI18N

        javax.swing.GroupLayout interactionPanelLayout = new javax.swing.GroupLayout(interactionPanel);
        interactionPanel.setLayout(interactionPanelLayout);
        interactionPanelLayout.setHorizontalGroup(
            interactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, interactionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pigImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        interactionPanelLayout.setVerticalGroup(
            interactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interactionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pigImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        helpButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        helpButton.setForeground(new java.awt.Color(50, 110, 211));
        helpButton.setText("help");
        helpButton.setBorder(null);
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        helpButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        infoButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        infoButton.setForeground(new java.awt.Color(50, 110, 211));
        infoButton.setText("info");
        infoButton.setBorder(null);
        infoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        infoButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        showButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        showButton.setForeground(new java.awt.Color(50, 110, 211));
        showButton.setText("show");
        showButton.setBorder(null);
        showButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        insertButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        insertButton.setForeground(new java.awt.Color(50, 110, 211));
        insertButton.setText("insert");
        insertButton.setBorder(null);
        insertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        insertButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        updateButton.setForeground(new java.awt.Color(50, 110, 211));
        updateButton.setText("update");
        updateButton.setBorder(null);
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        updateButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        removeButton.setForeground(new java.awt.Color(50, 110, 211));
        removeButton.setText("remove");
        removeButton.setBorder(null);
        removeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        removeButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        clearButton.setForeground(new java.awt.Color(50, 110, 211));
        clearButton.setText("clear");
        clearButton.setBorder(null);
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clearButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        executeScriptButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        executeScriptButton.setForeground(new java.awt.Color(50, 110, 211));
        executeScriptButton.setText("execute script");
        executeScriptButton.setBorder(null);
        executeScriptButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        executeScriptButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        executeScriptButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        executeScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeScriptButtonActionPerformed(evt);
            }
        });

        removeLowerButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        removeLowerButton.setForeground(new java.awt.Color(50, 110, 211));
        removeLowerButton.setText("remove lower");
        removeLowerButton.setBorder(null);
        removeLowerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeLowerButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        removeLowerButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        removeLowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLowerButtonActionPerformed(evt);
            }
        });

        replaceIfGreaterButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        replaceIfGreaterButton.setForeground(new java.awt.Color(50, 110, 211));
        replaceIfGreaterButton.setText("replace if greater");
        replaceIfGreaterButton.setBorder(null);
        replaceIfGreaterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        replaceIfGreaterButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        replaceIfGreaterButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        replaceIfGreaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceIfGreaterButtonActionPerformed(evt);
            }
        });

        removeGreaterButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        removeGreaterButton.setForeground(new java.awt.Color(50, 110, 211));
        removeGreaterButton.setText("remove greater");
        removeGreaterButton.setBorder(null);
        removeGreaterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeGreaterButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        removeGreaterButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        removeGreaterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeGreaterButtonActionPerformed(evt);
            }
        });

        countImpactSpeedButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        countImpactSpeedButton.setForeground(new java.awt.Color(50, 110, 211));
        countImpactSpeedButton.setText("count impact speed");
        countImpactSpeedButton.setBorder(null);
        countImpactSpeedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        countImpactSpeedButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countImpactSpeedButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        countImpactSpeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countImpactSpeedButtonActionPerformed(evt);
            }
        });

        filterCarButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        filterCarButton.setForeground(new java.awt.Color(50, 110, 211));
        filterCarButton.setText("filter car");
        filterCarButton.setBorder(null);
        filterCarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filterCarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        filterCarButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        filterCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterCarButtonActionPerformed(evt);
            }
        });

        uniqieMoodButton.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        uniqieMoodButton.setForeground(new java.awt.Color(50, 110, 211));
        uniqieMoodButton.setText("unique mood");
        uniqieMoodButton.setBorder(null);
        uniqieMoodButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uniqieMoodButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uniqieMoodButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        uniqieMoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniqieMoodButtonActionPerformed(evt);
            }
        });

        emptyResetButton.setBorder(null);
        emptyResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commandsButtonsPanelLayout = new javax.swing.GroupLayout(commandsButtonsPanel);
        commandsButtonsPanel.setLayout(commandsButtonsPanelLayout);
        commandsButtonsPanelLayout.setHorizontalGroup(
            commandsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandsButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commandsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(executeScriptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeLowerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(replaceIfGreaterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeGreaterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filterCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(commandsButtonsPanelLayout.createSequentialGroup()
                        .addGroup(commandsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(countImpactSpeedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uniqieMoodButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(commandsButtonsPanelLayout.createSequentialGroup()
                .addComponent(emptyResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        commandsButtonsPanelLayout.setVerticalGroup(
            commandsButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandsButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executeScriptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeLowerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceIfGreaterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeGreaterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countImpactSpeedButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterCarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uniqieMoodButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emptyResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usernameIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(commandsButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interactionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(interactionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commandsButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameIconLabel)
                            .addComponent(usernameLabel))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoButtonActionPerformed


    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showButtonActionPerformed


    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed

        interactionPanel.removeAll();
        interactionPanel.setLayout(new BoxLayout(interactionPanel, BoxLayout.Y_AXIS));

        HelpPanel helpPanel = new HelpPanel();
        helpPanel.setVisible(true);
        interactionPanel.add(helpPanel);

        // sending command request
        commandSender.sendCommand(new HelpCommand());

        // receiving command response
        try {
            String responseText = commandResponseReceiver.receiveCommandResponse();
            helpPanel.setText(("<html>" + responseText + "</html>").replace("\n", "<br>"));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        revalidate();
        repaint();
    }//GEN-LAST:event_helpButtonActionPerformed


    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertButtonActionPerformed


    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed


    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed


    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed


    private void executeScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeScriptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_executeScriptButtonActionPerformed


    private void removeLowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLowerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeLowerButtonActionPerformed


    private void replaceIfGreaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceIfGreaterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceIfGreaterButtonActionPerformed


    private void removeGreaterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeGreaterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeGreaterButtonActionPerformed


    private void countImpactSpeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countImpactSpeedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countImpactSpeedButtonActionPerformed


    private void filterCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterCarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterCarButtonActionPerformed


    private void uniqieMoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniqieMoodButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniqieMoodButtonActionPerformed


    private void emptyResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyResetButtonActionPerformed

        interactionPanel.removeAll();
        interactionPanel.add(pigImagePanel);

        revalidate();
        repaint();
    }//GEN-LAST:event_emptyResetButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel commandsButtonsPanel;
    private javax.swing.JButton countImpactSpeedButton;
    private javax.swing.JButton emptyResetButton;
    private javax.swing.JButton executeScriptButton;
    private javax.swing.JButton filterCarButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JPanel interactionPanel;
    private javax.swing.JLabel pigImagePanel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton removeGreaterButton;
    private javax.swing.JButton removeLowerButton;
    private javax.swing.JButton replaceIfGreaterButton;
    private javax.swing.JButton showButton;
    private javax.swing.JButton uniqieMoodButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel usernameIconLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
