/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.gui;

import client.CommandResponseReceiver;
import client.CommandSender;
import client.i10n.Resources;
import commonModule.collectionClasses.*;
import commonModule.commands.Command;
import commonModule.dataStructures.network.CommandRequest;
import commonModule.exceptions.InvalidCoordinatesException;
import commonModule.exceptions.InvalidInputException;
import commonModule.exceptions.commandExceptions.InvalidArgumentsException;
import commonModule.exceptions.serverExceptions.ServerIsDownException;
import commonModule.io.HumanBeingParser;

import javax.swing.*;
import java.util.Objects;
import java.util.ResourceBundle;


public class CommandWithObjectPanel extends javax.swing.JPanel {

    private Command command;
    private final CommandSender commandSender;
    private final CommandResponseReceiver commandResponseReceiver;

    public void setCommand(Command command) {
        this.command = command;
    }

    /**
     * Creates new form insertCommandPanel
     */
    public CommandWithObjectPanel(CommandSender commandSender, CommandResponseReceiver commandResponseReceiver) {
        this.commandSender = commandSender;
        this.commandResponseReceiver = commandResponseReceiver;

        initComponents();

        setLanguages();
    }


    private void setLanguages() {

        ResourceBundle resourceBundle = Resources.getResourceBundle();

        keyLabel.setText(resourceBundle.getString("key"));
        nameLabel.setText(resourceBundle.getString("name"));
        coordinatesLabel.setText(resourceBundle.getString("coordinates"));
        realHeroLabel.setText(resourceBundle.getString("realHero"));
        impactSpeedLabel.setText(resourceBundle.getString("impact_speed"));
        hasToothpickLabel.setText(resourceBundle.getString("hasToothpick"));
        carNameLabel.setText(resourceBundle.getString("carName"));
        carCoolLabel.setText(resourceBundle.getString("carCool"));
        moodLabel.setText(resourceBundle.getString("mood"));
        weaponLabel.setText(resourceBundle.getString("weapon"));

        moodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
                resourceBundle.getString("sadness"),
                resourceBundle.getString("apathy"),
                resourceBundle.getString("longing"),
                resourceBundle.getString("rage")
        }));

        weaponComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
                resourceBundle.getString("axe"),
                resourceBundle.getString("rifle"),
                resourceBundle.getString("knife")
        }));

        sendButton.setText(resourceBundle.getString("send"));
    }


    public JLabel getDoneLabel() {
        return doneLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        keyLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        keyTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        coordinatesLabel = new javax.swing.JLabel();
        coordinatesFieldName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        realHeroLabel = new javax.swing.JLabel();
        realHeroTextField = new javax.swing.JTextField();
        impactSpeedLabel = new javax.swing.JLabel();
        impactSpeedTextField = new javax.swing.JTextField();
        hasToothpickLabel = new javax.swing.JLabel();
        hasToothpickTextField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        carNameLabel = new javax.swing.JLabel();
        carNameTextField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        carCoolLabel = new javax.swing.JLabel();
        coolTextField = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        moodComboBox = new javax.swing.JComboBox<>();
        weaponComboBox = new javax.swing.JComboBox<>();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        moodLabel = new javax.swing.JLabel();
        weaponLabel = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        doneLabel = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("jMenu7");

        jMenuItem1.setText("jMenuItem1");

        jMenu8.setText("jMenu8");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar5.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar5.add(jMenu12);

        jMenu13.setText("jMenu13");

        popupMenu1.setLabel("popupMenu1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setPreferredSize(new java.awt.Dimension(678, 520));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(684, 520));

        keyLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        keyLabel.setForeground(new java.awt.Color(50, 110, 211));
        keyLabel.setText("key");
        keyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jSeparator1.setForeground(new java.awt.Color(50, 110, 211));

        keyTextField.setBackground(new java.awt.Color(238, 238, 238));
        keyTextField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        keyTextField.setForeground(new java.awt.Color(50, 110, 211));
        keyTextField.setBorder(null);
        keyTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        keyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyTextFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(50, 110, 211));
        nameLabel.setText("name");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        nameTextField.setBackground(new java.awt.Color(238, 238, 238));
        nameTextField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(50, 110, 211));
        nameTextField.setBorder(null);
        nameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        coordinatesLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        coordinatesLabel.setForeground(new java.awt.Color(50, 110, 211));
        coordinatesLabel.setText("coordinates");
        coordinatesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        coordinatesFieldName.setBackground(new java.awt.Color(238, 238, 238));
        coordinatesFieldName.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        coordinatesFieldName.setForeground(new java.awt.Color(50, 110, 211));
        coordinatesFieldName.setBorder(null);
        coordinatesFieldName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        coordinatesFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordinatesFieldNameActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(50, 110, 211));

        realHeroLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        realHeroLabel.setForeground(new java.awt.Color(50, 110, 211));
        realHeroLabel.setText("real hero (true / false)");
        realHeroLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        realHeroTextField.setBackground(new java.awt.Color(238, 238, 238));
        realHeroTextField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        realHeroTextField.setForeground(new java.awt.Color(50, 110, 211));
        realHeroTextField.setBorder(null);
        realHeroTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        realHeroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realHeroTextFieldActionPerformed(evt);
            }
        });

        impactSpeedLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        impactSpeedLabel.setForeground(new java.awt.Color(50, 110, 211));
        impactSpeedLabel.setText("impact speed");
        impactSpeedLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        impactSpeedTextField.setBackground(new java.awt.Color(238, 238, 238));
        impactSpeedTextField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        impactSpeedTextField.setForeground(new java.awt.Color(50, 110, 211));
        impactSpeedTextField.setBorder(null);
        impactSpeedTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        impactSpeedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impactSpeedTextFieldActionPerformed(evt);
            }
        });

        hasToothpickLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        hasToothpickLabel.setForeground(new java.awt.Color(50, 110, 211));
        hasToothpickLabel.setText("has toothpick (true / false)");
        hasToothpickLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        hasToothpickTextField.setBackground(new java.awt.Color(238, 238, 238));
        hasToothpickTextField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        hasToothpickTextField.setForeground(new java.awt.Color(50, 110, 211));
        hasToothpickTextField.setBorder(null);
        hasToothpickTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hasToothpickTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasToothpickTextFieldActionPerformed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(50, 110, 211));

        carNameLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        carNameLabel.setForeground(new java.awt.Color(50, 110, 211));
        carNameLabel.setText("car name");
        carNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        carNameTextField.setBackground(new java.awt.Color(238, 238, 238));
        carNameTextField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        carNameTextField.setForeground(new java.awt.Color(50, 110, 211));
        carNameTextField.setBorder(null);
        carNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        carNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carNameTextFieldActionPerformed(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(50, 110, 211));

        carCoolLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        carCoolLabel.setForeground(new java.awt.Color(50, 110, 211));
        carCoolLabel.setText("cool (true / false)");
        carCoolLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        coolTextField.setBackground(new java.awt.Color(238, 238, 238));
        coolTextField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        coolTextField.setForeground(new java.awt.Color(50, 110, 211));
        coolTextField.setBorder(null);
        coolTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        coolTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coolTextFieldActionPerformed(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(50, 110, 211));

        moodComboBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        moodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sadness", "longing", "apathy", "rage" }));
        moodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodComboBoxActionPerformed(evt);
            }
        });

        weaponComboBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        weaponComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "axe", "knife", "rifle" }));
        weaponComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weaponComboBoxActionPerformed(evt);
            }
        });

        jSeparator9.setForeground(new java.awt.Color(50, 110, 211));

        jSeparator10.setForeground(new java.awt.Color(50, 110, 211));

        jSeparator11.setForeground(new java.awt.Color(50, 110, 211));

        moodLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        moodLabel.setForeground(new java.awt.Color(50, 110, 211));
        moodLabel.setText("mood");
        moodLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        weaponLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        weaponLabel.setForeground(new java.awt.Color(50, 110, 211));
        weaponLabel.setText("weapon");
        weaponLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        sendButton.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        sendButton.setForeground(new java.awt.Color(50, 110, 211));
        sendButton.setText("Send");
        sendButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator8)
                        .addComponent(carCoolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(impactSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(realHeroLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hasToothpickLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameTextField)
                        .addComponent(coordinatesFieldName)
                        .addComponent(realHeroTextField)
                        .addComponent(impactSpeedTextField)
                        .addComponent(carNameTextField)
                        .addComponent(coolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(keyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasToothpickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordinatesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator9)
                    .addComponent(jSeparator10)
                    .addComponent(jSeparator11)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weaponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weaponComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(keyLabel)
                            .addComponent(moodLabel)
                            .addComponent(weaponLabel))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(moodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(weaponComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coordinatesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coordinatesFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(realHeroLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(realHeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(impactSpeedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(impactSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasToothpickLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasToothpickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carCoolLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        doneLabel.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        doneLabel.setForeground(new java.awt.Color(33, 209, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void coordinatesFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordinatesFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coordinatesFieldNameActionPerformed

    private void realHeroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realHeroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realHeroTextFieldActionPerformed

    private void impactSpeedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impactSpeedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_impactSpeedTextFieldActionPerformed

    private void hasToothpickTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasToothpickTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasToothpickTextFieldActionPerformed

    private void carNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carNameTextFieldActionPerformed

    private void coolTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coolTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coolTextFieldActionPerformed

    private void moodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moodComboBoxActionPerformed

    private void weaponComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weaponComboBoxActionPerformed

    private void keyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyTextFieldActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed

        doneLabel.setVisible(false);

        ResourceBundle resourceBundle = Resources.getResourceBundle();

        HumanBeing humanBeing = new HumanBeing();

        try {
            command.setArgs(new String[]{keyTextField.getText()});

            String name = HumanBeingParser.parseName(nameTextField.getText());
            humanBeing.setName(name);

            Coordinates coordinates = HumanBeingParser.parseCoordinates(coordinatesFieldName.getText());
            humanBeing.setCoordinates(coordinates);

        } catch (InvalidArgumentsException | InvalidInputException | InvalidCoordinatesException e) {
            JOptionPane.showMessageDialog(null, Resources.getResourceBundle().getString("error.InvalidInput") + ": \n" + e.getMessage());
            return;
        }

        // Mood mood = Mood.valueOf(Objects.requireNonNull(moodComboBox.getSelectedItem()).toString().toUpperCase());
        Mood mood = Mood.valueOf(resourceBundle.getString(Objects.requireNonNull(moodComboBox.getSelectedItem()).toString()).toUpperCase());
        humanBeing.setMood(mood);

        // WeaponType weaponType = WeaponType.valueOf(Objects.requireNonNull(weaponComboBox.getSelectedItem()).toString().toUpperCase());
        WeaponType weaponType = WeaponType.valueOf(resourceBundle.getString(Objects.requireNonNull(weaponComboBox.getSelectedItem()).toString()).toUpperCase());
        humanBeing.setWeaponType(weaponType);

        boolean realHero = Boolean.parseBoolean(realHeroTextField.getText());
        humanBeing.setRealHero(realHero);

        try {
            double impactSpeed = Double.parseDouble(impactSpeedTextField.getText());
            humanBeing.setImpactSpeed(impactSpeed);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, Resources.getResourceBundle().getString("error.ImpactSpeed"));
        }

        boolean hasToothpick = Boolean.parseBoolean(hasToothpickTextField.getText());
        humanBeing.setHasToothpick(hasToothpick);

        Car car = null;

        String carName = carNameTextField.getText();

        if (carName != null && !carName.isEmpty()) {
            car = new Car();
            car.setName(carName);
        }

        if (coolTextField.getText() != null && !coolTextField.getText().isEmpty()) {
            boolean cool = Boolean.parseBoolean(coolTextField.getText());
            if (car == null) {
                car = new Car();
            }
            car.setCool(cool);
        }

        humanBeing.setCar(car);

        command.setValue(humanBeing);

        commandSender.sendCommand(command);

        try {
            String response = commandResponseReceiver.receiveCommandResponse();
            if (response.equals("Done!")) {
                doneLabel.setText(Resources.getResourceBundle().getString("done"));
                doneLabel.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, Resources.getResourceBundle().getString("error.ResponseError") + "\n" + response);
            }
        } catch (ServerIsDownException e) {
            JOptionPane.showMessageDialog(null, Resources.getResourceBundle().getString("error.serverIsDown"));
        }
    }//GEN-LAST:event_sendButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carCoolLabel;
    private javax.swing.JLabel carNameLabel;
    private javax.swing.JTextField carNameTextField;
    private javax.swing.JTextField coolTextField;
    private javax.swing.JTextField coordinatesFieldName;
    private javax.swing.JLabel coordinatesLabel;
    private javax.swing.JLabel doneLabel;
    private javax.swing.JLabel hasToothpickLabel;
    private javax.swing.JTextField hasToothpickTextField;
    private javax.swing.JLabel impactSpeedLabel;
    private javax.swing.JTextField impactSpeedTextField;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JTextField keyTextField;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JComboBox<String> moodComboBox;
    private javax.swing.JLabel moodLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel realHeroLabel;
    private javax.swing.JTextField realHeroTextField;
    private javax.swing.JButton sendButton;
    private javax.swing.JComboBox<String> weaponComboBox;
    private javax.swing.JLabel weaponLabel;
    // End of variables declaration//GEN-END:variables
}
