package client.i10n;

import java.util.ListResourceBundle;

public class Resources_IS extends ListResourceBundle {

    private static final Object[][] contents = new Object[][] {
            {"language", "Tungumál"},
            {"login", "Skrá inn"},
            {"username", "Notendanafn"},
            {"password", "Lykilorð"},
            {"log_in", "Innskráning"},
            {"sign_up", "Nýskráning"},
            {"help", "Hjálp"},
            {"info", "Upplýsingar"},
            {"show", "Tafla"},
            {"insert", "Setja inn"},
            {"update", "Uppfæra"},
            {"remove", "Fjarlægja"},
            {"clear", "Hreinsa"},
            {"execute_script", "Keyra skipulagshefti"},
            {"remove_lower", "Fjarlægja minni"},
            {"replace_if_greater", "Skipta út ef stærri"},
            {"remove_greater", "Fjarlægja stærri"},
            {"count_impact_speed", "Fjölda áhrifshraða"},
            {"filter_car", "Sía bíla"},
            {"unique_mood", "Einstök skap"},
            {"key", "Lykill"},
            {"id", "Auðkenni"},
            {"name", "Nafn"},
            {"x_coordinate", "X hnit"},
            {"y_coordinate", "Y hnit"},
            {"coordinates", "innihald"},
            {"creation_date", "Búinn til"},
            {"mood", "Skap"},
            {"weapon", "Vopn"},
            {"realHero", "Ríkisborgari"},
            {"hasToothpick", "Hefur tannstöngul"},
            {"impact_speed", "Áhrifshraði"},
            {"carName", "Bílnafn"},
            {"carCool", "Kúl bíll"},
            {"sadness", "Sorg"},
            {"longing", "Lengtan"},
            {"apathy", "Hlutlausni"},
            {"rage", "Reiði"},
            {"axe", "Öxi"},
            {"knife", "Nífur"},
            {"rifle", "Byssa"},
            {"send", "Senda"},
            {"russian", "Rússneska"},
            {"ukrainian", "Úkraínska"},
            {"icelandic", "Íslenska"},
            {"spanish", "Spænska"},
            {"result", "niðurstaða"},
            {"script_path", "slóð að handriti"},
            {"done", "Búið!"},
            {"account_question", "  Ertu ekki með aðgang?"},
            {"Tungumál", "language"},
            {"Skrá inn", "login"},
            {"Notendanafn", "username"},
            {"Lykilorð", "password"},
            {"Innskráning", "log_in"},
            {"Nýskráning", "sign_up"},
            {"Hjálp", "help"},
            {"Upplýsingar", "info"},
            {"Tafla", "show"},
            {"Setja inn", "insert"},
            {"Uppfæra", "update"},
            {"Fjarlægja", "remove"},
            {"Hreinsa", "clear"},
            {"Keyra skipulagshefti", "execute_script"},
            {"Fjarlægja minni", "remove_lower"},
            {"Skipta út ef stærri", "replace_if_greater"},
            {"Fjarlægja stærri", "remove_greater"},
            {"Fjölda áhrifshraða", "count_impact_speed"},
            {"Sía bíla", "filter_car"},
            {"Einstök skap", "unique_mood"},
            {"Lykill", "key"},
            {"Auðkenni", "id"},
            {"Nafn", "name"},
            {"X hnit", "x_coordinate"},
            {"Y hnit", "y_coordinate"},
            {"innihald", "coordinates"},
            {"Búinn til", "creation_date"},
            {"Skap", "mood"},
            {"Vopn", "weapon"},
            {"Ríkisborgari", "realHero"},
            {"Hefur tannstöngul", "hasToothpick"},
            {"Áhrifshraði", "impact_speed"},
            {"Bílnafn", "carName"},
            {"Kúl bíll", "carCool"},
            {"Sorg", "sadness"},
            {"Lengtan", "longing"},
            {"Hlutlausni", "apathy"},
            {"Reiði", "rage"},
            {"Öxi", "axe"},
            {"Nífur", "knife"},
            {"Byssa", "rifle"},
            {"Senda", "send"},
            {"Rússneska", "russian"},
            {"Úkraínska", "ukrainian"},
            {"Íslenska", "icelandic"},
            {"Spænska", "spanish"},
            {"niðurstaða", "result"},
            {"slóð að handriti", "script_path"},
            {"Búið!", "done"},
            {" Ertu ekki með aðgang?", "account_question"},

            {"error.script_recursion", "Þú getur ekki keyrt skriftur endurkvæmt!"},
            {"error.noSuchFile", "Skrá finnst ekki"},
            {"error.serverIsDown", "Villa við tengingu við miðlara"},
            {"error.InvalidInputException", "Rangir gögn"},
            {"error.InvalidPassword", "Rangt lykilorð"},
            {"error.ImpactSpeed", "Hraði verður að vera tala"},
            {"error.ResponseError", "Villa kom upp við að framkvæma beiðni "},
            {"error.InvalidArguments", "Ógild gögn"},
            {"error.AccessError", "Þú hefur ekki aðgang að því að breyta þessum stillingi"},
            {"error.EmptyName", "Nafn má ekki vera tómt"},
            {"error.CoordinateFormat", "Hnitin verða að vera tala"},
            {"error.MoodError", "Ógild gildi fyrir ástand"},
            {"error.CarCoolError", "carCool verður að vera rétt eða röng"},
            {"error.HasToothpick", "hasToothpick verður að vera rétt eða röng"},
            {"error.RealHero", "realHero verður að vera rétt / 1 eða röng / 0"},
            {"error.WeaponType", "Ógilt gildi fyrir vopn"},
            {"error.", ""},
            {"error.", ""},
            {"error.", ""},
            {"error.", ""}
    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }
}
