package client.i10n;


import java.util.ListResourceBundle;

public class Resources_DO extends ListResourceBundle {

    private static final Object[][] contents = new Object[][] {
            {"language", "Idioma"},
            {"login", "Iniciar sesión"},
            {"username", "Nombre de usuario"},
            {"password", "Contraseña"},
            {"log_in", "Entrar"},
            {"sign_up", "Registrarse"},
            {"help", "Ayuda"},
            {"info", "Información"},
            {"show", "Tabla"},
            {"insert", "Insertar"},
            {"update", "Actualizar"},
            {"remove", "Eliminar"},
            {"clear", "Limpiar"},
            {"execute_script", "Ejecutar script"},
            {"remove_lower", "Eliminar menores"},
            {"replace_if_greater", "Reemplazar si es mayor"},
            {"remove_greater", "Eliminar mayores"},
            {"count_impact_speed", "Contar velocidad de impacto"},
            {"filter_car", "Filtrar por coches"},
            {"unique_mood", "Estados de ánimo únicos"},
            {"key", "Clave"},
            {"id", "Id"},
            {"name", "Nombre"},
            {"x_coordinate", "Coordenada X"},
            {"y_coordinate", "Coordenada Y"},
            {"coordinates", "coordenadas"},
            {"creation_date", "Fecha de creación"},
            {"mood", "Estado de ánimo"},
            {"weapon", "Arma"},
            {"realHero", "Héroe real"},
            {"hasToothpick", "Tiene palillo de dientes"},
            {"impact_speed", "Velocidad de impacto"},
            {"carName", "Marca de coche"},
            {"carCool", "Coche chulo"},
            {"sadness", "Tristeza"},
            {"longing", "Anhelo"},
            {"apathy", "Apatía"},
            {"rage", "Ira"},
            {"axe", "Hacha"},
            {"knife", "Cuchillo"},
            {"rifle", "Rifle"},
            {"send", "Enviar"},
            {"russian", "Ruso"},
            {"ukrainian", "Ucraniano"},
            {"icelandic", "Islandés"},
            {"spanish", "Español"},
            {"result", "resultado"},
            {"script_path", "ruta al script"},
            {"done", "¡Hecho!"},
            {"account_question", "   ¿No tienes una cuenta?"},
            {"Idioma", "language"},
            {"Iniciar sesión", "login"},
            {"Nombre de usuario", "username"},
            {"Contraseña", "password"},
            {"Entrar", "log_in"},
            {"Registrarse", "sign_up"},
            {"Ayuda", "help"},
            {"Información", "info"},
            {"Tabla", "show"},
            {"Insertar", "insert"},
            {"Actualizar", "update"},
            {"Eliminar", "remove"},
            {"Limpiar", "clear"},
            {"Ejecutar script", "execute_script"},
            {"Eliminar menores", "remove_lower"},
            {"Reemplazar si es mayor", "replace_if_greater"},
            {"Eliminar mayores", "remove_greater"},
            {"Contar velocidad de impacto", "count_impact_speed"},
            {"Filtrar por coches", "filter_car"},
            {"Estados de ánimo únicos", "unique_mood"},
            {"Clave", "key"},
            {"Id", "id"},
            {"Nombre", "name"},
            {"Coordenada X", "x_coordinate"},
            {"Coordenada Y", "y_coordinate"},
            {"coordenadas", "coordinates"},
            {"Fecha de creación", "creation_date"},
            {"Estado de ánimo", "mood"},
            {"Arma", "weapon"},
            {"Héroe real", "realHero"},
            {"Tiene palillo de dientes", "hasToothpick"},
            {"Velocidad de impacto", "impact_speed"},
            {"Marca de coche", "carName"},
            {"Coche chulo", "carCool"},
            {"Tristeza", "sadness"},
            {"Anhelo", "longing"},
            {"Apatía", "apathy"},
            {"Ira", "rage"},
            {"Hacha", "axe"},
            {"Cuchillo", "knife"},
            {"Rifle", "rifle"},
            {"Enviar", "send"},
            {"Ruso", "russian"},
            {"Ucraniano", "ukrainian"},
            {"Islandés", "icelandic"},
            {"Español", "spanish"},
            {"resultado", "result"},
            {"ruta al script", "script_path"},
            {"¡Hecho!", "done"},
            {" ¿No tienes una cuenta?", "account_question"},


            {"error.script_recursion", "¡No puede ejecutar scripts de forma recursiva!"},
            {"error.noSuchFile", "Archivo no encontrado"},
            {"error.serverIsDown", "Error al conectar con el servidor"},
            {"error.InvalidInputException", "Datos incorrectos"},
            {"error.InvalidPassword", "Contraseña incorrecta"},
            {"error.ImpactSpeed", "La velocidad debe ser un número"},
            {"error.ResponseError", "Se produjo un error al realizar la solicitud "},
            {"error.InvalidArguments", "Argumentos no válidos"},
            {"error.AccessError", "No tiene acceso para modificar este parámetro"},
            {"error.EmptyName", "El nombre no puede estar vacío"},
            {"error.CoordinateFormat", "La coordenada debe ser un número"},
            {"error.MoodError", "Valor de estado de ánimo no válido"},
            {"error.CarCoolError", "carCool debe ser verdadero o falso"},
            {"error.HasToothpick", "hasToothpick debe ser verdadero o falso"},
            {"error.RealHero", "realHero debe ser verdadero / 1 o falso / 0"},
            {"error.WeaponType", "Valor de arma no válido"},
            {"error.", ""},
            {"error.", ""},
            {"error.", ""},
            {"error.", ""}
    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }
}

