package client.i10n;

import java.util.ListResourceBundle;

public class Resources_UA extends ListResourceBundle {

    private static final Object[][] contents = new Object[][] {
            {"language", "Мова"},
            {"login", "Авторизація"},
            {"username", "Ім'я користувача"},
            {"password", "Пароль"},
            {"log_in", "Увійти"},
            {"sign_up", "Реєстрація"},
            {"help", "Допомога"},
            {"info", "Інформація"},
            {"show", "Таблиця"},
            {"insert", "Вставити"},
            {"update", "Оновити"},
            {"remove", "Видалити"},
            {"clear", "Очистити"},
            {"execute_script", "Виконати скрипт"},
            {"remove_lower", "Видалити менші"},
            {"replace_if_greater", "Замінити якщо більше"},
            {"remove_greater", "Видалити більші"},
            {"count_impact_speed", "Порахувати швидкість"},
            {"filter_car", "Фільтр по машинам"},
            {"unique_mood", "Унікальні настрої"},
            {"key", "Ключ"},
            {"id", "Ідентифікатор"},
            {"name", "Ім'я"},
            {"coordinates", "координата"},
            {"x_coordinate", "X координата"},
            {"y_coordinate", "Y координата"},
            {"creation_date", "Дата створення"},
            {"mood", "Настрій"},
            {"weapon", "Зброя"},
            {"realHero", "Герой"},
            {"hasToothpick", "Є зубочистка"},
            {"impact_speed", "Швидкість"},
            {"carName", "Марка машини"},
            {"carCool", "Крута машина"},
            {"sadness", "Сум"},
            {"longing", "Туга"},
            {"apathy", "Апатія"},
            {"rage", "Злість"},
            {"axe", "Топір"},
            {"knife", "Ніж"},
            {"rifle", "Гвинтівка"},
            {"send", "Відправити"},
            {"russian", "Російська"},
            {"ukrainian", "Українська"},
            {"icelandic", "Ісландська"},
            {"spanish", "Іспанська"},
            {"result", "результат"},
            {"script_path", "шлях до скрипта"},
            {"done", "Зроблено!"},
            {"account_question", "      Ще немає аккаунту?"},
            {"Мова", "language"},
            {"Авторизація", "login"},
            {"Ім'я користувача", "username"},
            {"Пароль", "password"},
            {"Увійти", "log_in"},
            {"Реєстрація", "sign_up"},
            {"Допомога", "help"},
            {"Інформація", "info"},
            {"Таблиця", "show"},
            {"Вставити", "insert"},
            {"Оновити", "update"},
            {"Видалити", "remove"},
            {"Очистити", "clear"},
            {"Виконати скрипт", "execute_script"},
            {"Видалити менші", "remove_lower"},
            {"Замінити якщо більше", "replace_if_greater"},
            {"Видалити більші", "remove_greater"},
            {"Порахувати швидкість", "count_impact_speed"},
            {"Фільтр по машинам", "filter_car"},
            {"Унікальні настрої", "unique_mood"},
            {"Ключ", "key"},
            {"Ідентифікатор", "id"},
            {"Ім'я", "name"},
            {"координата", "coordinates"},
            {"X координата", "x_coordinate"},
            {"Y координата", "y_coordinate"},
            {"Дата створення", "creation_date"},
            {"Настрій", "mood"},
            {"Зброя", "weapon"},
            {"Герой", "realHero"},
            {"Є зубочистка", "hasToothpick"},
            {"Швидкість", "impact_speed"},
            {"Марка машини", "carName"},
            {"Крута машина", "carCool"},
            {"Сум", "sadness"},
            {"Туга", "longing"},
            {"Апатія", "apathy"},
            {"Злість", "rage"},
            {"Топір", "axe"},
            {"Ніж", "knife"},
            {"Гвинтівка", "rifle"},
            {"Відправити", "send"},
            {"Російська", "russian"},
            {"Українська", "ukrainian"},
            {"Ісландська", "icelandic"},
            {"Іспанська", "spanish"},
            {"результат", "result"},
            {"шлях до скрипта", "script_path"},
            {"Зроблено!", "done!"},
            {" Ще немає аккаунту?", "account_question"},

            {"error.script_recursion", "Вы не можете выполнять скрипты рекурсивно!"},
            {"error.noSuchFile", "Файл не найден"},
            {"error.serverIsDown", "Ошибка при подключении к серверу"},
            {"error.InvalidInputException", "Некорректные данные"},
            {"error.InvalidPassword", "Неверный пароль"},
            {"error.ImpactSpeed", "Скорость должна быть числом"},
            {"error.ResponseError", "При выполнении запроса возникла ошибка "},
            {"error.InvalidArguments", "Некорректные аргументы"},
            {"error.AccessError", "У вас нет доступа к изменению этого параметра"},
            {"error.EmptyName", "Имя не может быть пустым"},
            {"error.CoordinateFormat", "Координата должны быть числом"},
            {"error.MoodError", "Некорректное значение настроения"},
            {"error.CarCoolError", "carCool должно быть true или false"},
            {"error.HasToothpick", "hasToothpick должен быть true или false"},
            {"error.RealHero", "realHero должен быть true / 1 или false / 0"},
            {"error.WeaponType", "Некорректное значение оружия"},
            {"error.", ""},
            {"error.", ""},
            {"error.", ""},
            {"error.", ""}
    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }

}
